In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
data = np.load("/content/drive/MyDrive/ml1/train.npy", allow_pickle=True)
data = data.item()
data_input = data['input']

In [3]:
labels = data['label']

In [4]:
data_input.shape

(1080, 256, 64, 1)

In [5]:
labels

array([1., 1., 1., ..., 0., 0., 0.])

In [6]:
labels = data['label']
labels.shape
repeated_arr = []
for i in range(len(labels)):
    repeated_arr.extend(np.full(64, labels[i]))

labels_1 = np.array(repeated_arr)
labels_1.shape





(69120,)

In [7]:
labels_1.shape

(69120,)

In [8]:
input_T = []
for i in range(1080):
    data_input_m = data_input[i][:][:].squeeze().T
    input_T.append(data_input_m)

input_T = np.array(input_T)
input_T.shape

(1080, 64, 256)

In [9]:
sclaer = StandardScaler()
data_input_0 = input_T.reshape(1080*64,256)
data_input_1 = sclaer.fit_transform(data_input_0)

In [10]:
data_input_1.shape

(69120, 256)

In [11]:
labels_1.mean()

0.5

In [12]:
# 라이브러리 설치
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 데이터 준비

X = data_input_1
y = labels_1


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# 모델 생성
model = RandomForestClassifier(n_estimators=100)

# 모델 학습
model.fit(X_train, y_train)

# 모델 평가
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
y_pred

Accuracy: 0.8414351851851852


array([0., 0., 1., ..., 1., 1., 1.])

In [13]:
data_test = np.load("/content/drive/MyDrive/ml1/test.npy", allow_pickle=True)
data_test = data_test.item()
data_input_test = data_test['input']

In [14]:
input_test_T = []
for i in range(120):
    data_input_m = data_input_test[i][:][:].squeeze().T
    input_test_T.append(data_input_m)

input_test_T = np.array(input_test_T)
input_test_T.shape

(120, 64, 256)

In [15]:
data_input_0_test = data_input_test.reshape(120*64,256)
data_input_1_test = sclaer.fit_transform(data_input_0_test)

In [16]:
data_input_1_test.shape

(7680, 256)

In [17]:
y_pred = model.predict(data_input_1_test)

In [18]:
y_pred.mean()

0.5049479166666667

In [19]:
csv = list(y_pred)

In [20]:
len(csv)

7680

In [21]:
answer = []

for i in range(120):
    pred = []
    for s in range(64):
        pred.append(csv[i*64+s])
    if sum(pred)/len(pred) > 0.5:
        answer.append(1)
    else:
        answer.append(0)

len(answer)

120

In [22]:
answer

[0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0]

In [23]:
test_pred = np.array(answer)

In [24]:
test_pred

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0])

In [25]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [26]:
df = pd.DataFrame(answer)

In [27]:
df.to_csv('submission_1.csv',index = True)