In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [ ]:
data = np.load("/content/drive/MyDrive/ml1/train.npy", allow_pickle=True)
data = data.item()
data_input = data['input']

In [ ]:
labels = data['label']

In [ ]:
data_input.shape

(1080, 256, 64, 1)

In [ ]:
labels

array([1., 1., 1., ..., 0., 0., 0.])

# 전처리


In [ ]:
labels = data['label']
labels.shape
repeated_arr = []
for i in range(len(labels)):
    repeated_arr.extend(np.full(64, labels[i]))

labels_1 = np.array(repeated_arr)
labels_1





array([1., 1., 1., ..., 0., 0., 0.])

In [ ]:
labels_1.shape

(69120,)

In [ ]:
input_T = []
for i in range(1080):
    data_input_m = data_input[i][:][:].squeeze().T
    input_T.append(data_input_m)

input_T = np.array(input_T)
input_T.shape

(1080, 64, 256)

In [ ]:
data_input_0 = input_T.reshape(1080*64,256)
df = pd.DataFrame(data_input_0)
data_input_0.shape

(69120, 256)

In [ ]:
69120-66270

2850

In [ ]:
import pandas as pd



# IQR 계산
q1 = df[0].quantile(0.25)
q3 = df[0].quantile(0.75)
iqr = q3 - q1

# 이상치 범위 설정
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

# 이상치 찾기
outliers = df[(df[0] <= lower_bound) | (df[0] >= upper_bound)]






row_index = outliers.index.tolist()

In [ ]:
max(row_index)

69069

In [ ]:
len(row_index)

2939

In [ ]:
data_input_list = list(data_input_0)
label_list = list(labels_1)

In [ ]:
print(len(data_input_list),len(label_list))

66181 66181


In [ ]:
for i in reversed(row_index):
    data_input_list.pop(i)
    label_list.pop(i)

In [ ]:
data_input_cut = np.array(data_input_list)
labels_cut = np.array(label_list)

정규화


In [ ]:
sclaer = StandardScaler()

data_input_1 = sclaer.fit_transform(data_input_0)

In [ ]:
labels_1.mean()

0.5

In [ ]:
plt.boxplot(data_input_1)

plt.show()

In [ ]:
labels_cut.mean()

0.5039815052658618

----


----

-----

----

----

----

----

# 학습


In [ ]:
X = data_input_cut
y = labels_cut

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

# 그래디언트 부스팅 모델 초기화 및 설정
gb_model = GradientBoostingClassifier(n_estimators=300, learning_rate=0.03, max_depth=9, subsample=0.7, min_samples_leaf=3, random_state=0)





# 모델 학습
gb_model.fit(X, y)

# 테스트 데이터에 대한 예측

y2_train_hat = gb_model.predict(X)

# 정확도 평가


train_accuracy = accuracy_score(y, y2_train_hat)
print("train 데이터 정확도:", train_accuracy )



train 데이터 정확도: 0.9788307822486817


In [ ]:
# 라이브러리 설치
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 데이터 준비

X = data_input_cut
y = labels_cut





# 모델 생성
model = RandomForestClassifier(n_estimators=100)

# 모델 학습
model.fit(X, y)

# 모델 평가


Accuracy: 0.9999565972222222


array([1., 1., 1., ..., 0., 0., 0.])

In [ ]:
answer_0 = []

for i in range(120):
    pred_0 = []
    for s in range(64):
        pred_0.append(y_pred_0[i*64+s])
    if sum(pred_0)/len(pred_0) > 0.5:
        answer_0.append(1)
    else:
        answer_0.append(0)

len(answer_0)

y_test_120 = []
for i in range(120):
    y_test_0 = []
    for s in range(64):
        y_test_0.append(y_test[i*64+s])
    if sum(y_test_0)/len(y_test_0) > 0.5:
        y_test_120.append(1)
    else:
        y_test_120.append(0)


----


----

----

----

#*TEST 파일 load 및 csv export*#


In [ ]:
data_test = np.load("/content/drive/MyDrive/ml1/test.npy", allow_pickle=True)
data_test = data_test.item()
data_input_test = data_test['input']

In [ ]:
input_test_T = []
for i in range(120):
    data_input_m = data_input_test[i][:][:].squeeze().T
    input_test_T.append(data_input_m)

input_test_T = np.array(input_test_T)
input_test_T.shape

(120, 64, 256)

In [ ]:
data_input_0_test = data_input_test.reshape(120*64,256)
data_input_1_test = sclaer.fit_transform(data_input_0_test)

In [ ]:
data_input_1_test.shape

(7680, 256)

In [ ]:
y_pred = gb_model.predict(data_input_0_test)

In [ ]:
y_pred

array([1., 1., 1., ..., 1., 1., 0.])

In [ ]:
y_pred.mean()

0.823828125

In [ ]:
csv = list(y_pred)

array([1., 1., 1., ..., 0., 0., 0.])

In [ ]:
len(csv)

7680

In [ ]:
answer = []

for i in range(120):
    pred = []
    for s in range(64):
        pred.append(csv[i*64+s])
    if sum(pred)/len(pred) > 0.5:
        answer.append(1)
    else:
        answer.append(0)

len(answer)

120

In [ ]:
test_pred = np.array(answer)

In [ ]:
test_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.DataFrame(answer)

In [ ]:
df.to_csv('submission_11.csv',index = True)